stages:
  - build
  - test
  - deploy_staging

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"

deploy-staging:
  stage: deploy_staging
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$STAGING_ENV --api-key=$HEROKU_API_KEY
